// front/src/components/Rooms.tsx
import React from 'react';
import Logo from "./Logo";
import Footer from "./Footer";
import {SocketContext} from "../socket/SocketProvider";


class Rooms extends React.Component {
  static contextType = SocketContext
  state = {
    loading: true,
    rooms: [],
  }


  handleSubmit = (event: { stopPropagation: () => void; preventDefault: () => void; }) => {
    event.stopPropagation()
    event.preventDefault()

    // @ts-ignore
    this.context.emit('update-player-data', {name: this.state.playerName, color: this.state.playerColor})
    this.setState({'formSubmitted': true})
  }

  componentDidMount() {
    // @ts-ignore
    this.context.emit('rooms-refresh')

    // @ts-ignore
    this.context.on('rooms-refresh-result', (result) => {
      this.setState({loading: false, rooms: result.data})
    })
  }

  render() {
    const {loading, rooms} = this.state

    return (
      <div className="super-wrapper">
        <section className="wrapper">
          <Logo/>

          <h3>Rooms list</h3>
          <div className="page-rooms__intro">
            <p className="text-center">
              <a className="user-name" href="#" id="playerNameLabel"
                //style="{ color: playerData ? playerData.color : null }"
              >
                <span>Player name</span>
              </a>
            </p>
            <p>You first need to select a room or create a new one</p>
          </div>
          <a id="rooms-refresh" href="#">[Refresh]</a
          >
          <div className="rooms-list">
            <h3 className="rooms-list__title">Join a room…</h3>

            <div id="rooms-holder">
              {loading &&
                <p>
                  Loading rooms...
                </p>
              }
              {!loading && rooms &&
                <ul className="rooms-list__list">
                  <li>
                    <a className="rooms-list__link" href="#">Room 1</a>
                  </li>
                </ul>
              }
              {loading && !rooms &&
                <p className="rooms-list__no-rooms">No rooms yet :(</p>
              }

            </div>
          </div>

          <form className="sq-form" method="post" action="#">
            <div className="input-field">
              <label htmlFor="newRoom">Or create a new one?</label>
              <input id="newRoom" placeholder="Give it a name" required type="text"/>
            </div>
            <div className="input-field input-submit text-center">
              <button className="btn" type="submit">Create room</button>
            </div>
          </form>

        </section>
        <Footer/>
      </div>
    );
  }
}

export default Rooms;

// vueapp/src/components/Rooms.vue
<template>
  <div class="super-wrapper">
    <div class="particles-js" id="particles-js">
      <canvas
        class="particles-js-canvas-el"
        width="1905"
        height="525"
        style="width: 100%; height: 100%;"
      ></canvas>
    </div>
    <section class="wrapper">
      <Logo />

      <h3>Rooms list</h3>
      <div class="page-rooms__intro">
        <p class="text-center">
          <a
            class="user-name"
            href="/"
            id="playerNameLabel"
            :style="{ color: playerData ? playerData.color : null }"
            ><span>{{ playerData ? playerData.name : null }}</span></a
          >
        </p>
        <p>You first need to select a room or create a new one</p>
      </div>
      <a id="rooms-refresh" href="#" @click="refreshRooms">[Refresh]</a>
      <div class="rooms-list">
        <h3 class="rooms-list__title">Join a room…</h3>
        <div id="rooms-holder">
          <ul v-if="rooms" class="rooms-list__list">
            <li v-for="room in rooms" :key="room.id" class="rooms-list__item">
              <a class="rooms-list__link" :href="'rooms/' + room.slug">{{
                room.name
              }}</a>
            </li>
          </ul>
          <p v-else class="rooms-list__no-rooms">No rooms yet :(</p>
        </div>
      </div>
      <form class="sq-form" method="post" action="#" @submit="checkForm">
        <div class="input-field">
          <label for="newRoom">Or create a new one?</label
          ><input
            id="newRoom"
            placeholder="Give it a name"
            type="text"
            v-model="newRoomName"
          />
        </div>
        <div class="input-field input-submit text-center">
          <button class="btn" type="submit">Create room</button>
        </div>
      </form>
    </section>
    <Footer />
  </div>
</template>

<script>
import Logo from './common/Logo'
import Footer from './common/Footer'
export default {
  name: 'Rooms',
  data() {
    return {
      rooms: [],
      newRoomName: null
    }
  },
  created() {
    if (this.$store.state.playerData === null) {
      this.$router.push('/')
    }

    this.$store.state.socket.on('rooms-refresh-result', (result) => {
      if (!result.success) {
        alert(result.error)
        return
      }

      this.rooms = result.data
    })

    this.$store.state.socket.on('rooms-create-result', (result) => {
      if (!result.success) {
        alert(result.error)
        return
      }

      this.$router.push('/rooms/' + result.data.roomSlug)
    })
  },
  components: {
    Logo,
    Footer
  },
  methods: {
    refreshRooms() {
      this.$store.state.socket.emit('rooms-refresh')
    },
    checkForm(e) {
      e.preventDefault()
      this.$store.state.socket.emit('rooms-create', this.newRoomName)
    }
  },
  computed: {
    playerData() {
      return this.$store.state.playerData
    }
  }
}
</script>

<style></style>
